apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: 117227220849.dkr.ecr.us-east-1.amazonaws.com/jenkins-ecr-1:tagVersion
          ports:
            - containerPort: 8080
