apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: 117227220849.dkr.ecr.us-east-1.amazonaws.com/jenkins-ecr-1:v1
      ports:
        - containerPort: 8080
